@startuml ToDoList

title TP - TODO List - Grupo 9
skinparam lineType ortho

class Aplicacion{
    - gestorDeTarea: GestorDeTarea
    - gestorDeEstadisticas: GestorDeEstadisticas
    - categorias: Array<Categoria>
    - etiquetas: Array<Etiqueta>
}

class GestorDeEstadisticas{
    - Array<Tarea>
    + tiempoPromedioDedicadoALasTareas(tareas: Array<Tarea>): datetime
    + cantidadDeTareasPorEstado(tareas: Array<Tarea>): Map<string, cantidad>
    + CantidadDeTareasPorCategoría(tareas: Array<Tarea>): Map<string, cantidad>
}

class GestorDeNotificaciones{
    + notificarRecordatorio()
}

class Tarea{
    - titulo: string
    - descripcion: string
    - fechaVencimiento: Date
    - fechaCreacion: Date
    - prioridad: Prioridad
    - avance: Avance
    - estado: Estado
    - categoría: Categoria
    - etiquetas: Etiqueta[]
    
    + setTitulo(titulo: string): void
    + getTitulo(): string
    + setDescripcion(desc: string): void
    + getDescripcion(): string
    + getFechaCreacion(): Date
    + setFechaVencimiento(fecha: Date): void
    + getFechaVencimiento(): Date
    + setPrioridad(prioridad: Prioridad): void
    + getPrioridad(): Prioridad
    + setAvance(avance: Avance): void
    + getAvance(): Avance
    + setEstado(estado: Estado): void
    + getEstado(): Estado
    + setCategoria(categoria: Categoria): void
    + getCategoria(): Categoria
    + setEtiqueta(etiqueta: Etiqueta): void
    + getEtiquetas(): Etiqueta[]
}

ENUM Estado{
    Pendiente
    EnProgreso
    Completado
}

ENUM Avance{
    0
    25
    50
    75
    100
}

ENUM Prioridad{
    Alta
    Media
    Baja
}

class GestorDeTarea{
    - tareas: Array<Tarea>
    + crearTarea(tarea: Tarea): void
    + eliminarTarea(tarea: Tarea): void
    + editarTarea(tarea: Tarea): void
    + ordenarTareasPorPrioridad(): Tarea[]
    + ordenarTareasPorFecha(): Tarea[]
    + buscarTareaPorTitulo(titulo: string): Tarea | null
    + getTareasCompletadas(): Tarea[]
    + getTareasPendientes(): Tarea[]
}

Aplicacion <-- GestorDeTarea
Aplicacion <-- GestorDeEstadisticas
Aplicacion <-- GestorDeNotificaciones
GestorDeEstadisticas --> Tarea
GestorDeTarea --> Tarea
Tarea -right-* Aplicacion
Tarea o-up- Prioridad
Tarea o-up- Estado
Tarea o-up- Avance
@enduml