@startuml ToDoList

title TP - TODO List - Grupo 9
skinparam lineType ortho

class Tarea{
   - id: number
   - titulo: string
   - descripcion: string
   - fechaCreacion: Moment
   - fechaVencimiento: Moment
   - prioridad: Prioridad
   - avance: Avance
   - estados: Map<Estado,Moment>
   - estadoActual: Estado
   - categoria: Categoria | undefined
   - etiquetas: Etiqueta[]
    
    + setTitulo(): void
    + getTitulo(): number
    + setTitulo(titulo: string): void
    + getTitulo(): string
    + setDescripcion(desc: string): void
    + getDescripcion(): string
    + getFechaCreacion(): Date
    + setFechaVencimiento(fecha: Date): void
    + getFechaVencimiento(): Date
    + setPrioridad(prioridad: Prioridad): void
    + getPrioridad(): Prioridad
    + setAvance(avance: Avance): void
    + getAvance(): Avance
    + setEstado(estado: Estado): void
    + getEstadoActual(): Estado
    + getEstados(): Map<Estado,Moment>
    + setCategoria(categoria: Categoria): void
    + getCategoria(): Categoria | undefined
    + setEtiqueta(etiqueta: Etiqueta): void
    + getEtiquetas(): Etiqueta[]
    + eliminarEtiquetaDeLista(nombre: string): void
}

class CreadorDeTarea{
    + instanciarTarea(): Tarea
}

class GestorDeTarea{
    - tareas: Array<Tarea>
    - categorias: Array<Categoria>
    - etiquetas: Array<Etiqueta>
    - creadorDeTareas: CreadorDeTarea
    - creadorDeClasificador: CreadorDeClasificador

    - errorIdNoEncontrado(idTarea: number): void
    - obtenerTareaPorId(idTarea: number): Tarea | undefined
    + agregarTareaALista(): void
    + agregarCategoriaALista(nombre: string): void
    + agregarEtiquetaALista(nombre: string): void
    + eliminarTareaDeLista(id: number): void
    + eliminarCategoriaDeLista(nombre: string): void
    + eliminarEtiquetaDeLista(nombre: string): void
    + editarTituloDeTarea(idTarea: number, nuevoTitulo: string): void
    + editarDescripcionDeTarea(idTarea: number, nuevaDescripcion: string): void
    + editarFechaDeVencimientoDeTarea(idTarea: number, year: number, month: number, day: number): void
    + editarPrioridadDeTarea(idTarea: number, prioridad: PRIORIDAD): void
    + editarAvanceDeTarea(idTarea: number, avance: AVANCE): void
    + editarEstadoDeTarea(idTarea: number, estado: ESTADO): void
    + editarCategoriaDeTarea(idTarea: number, nombreDeCategoria: string): void
    + agregarEtiquetaATarea(idTarea: number, nombreDeEtiqueta: string): void
    + eliminarEtiquetaDeTarea(idTarea: number, nombreDeEtiqueta: string): void
}

class BuscadorDeTarea{
    - tareas: Array<Tarea>

    + getTareaPorTitulo(titulo: string): Tarea | undefined
    + getTareasCompletadas(): Tarea[]
    + getTareasNoCompletadas(): Tarea[]
    + getTareasPendientes(): Tarea[]
    + getTareasXEtiquetas(etiqueta: Etiqueta): Tarea[]
    + getTareasXFechaDeVencimiento(fechaVencimiento: Moment): Tarea[]
}

class OrganizadorDeTarea{
    - tareas: Array<Tarea>

    + ordenarTareasPorPrioridad(): Tarea[]
    + ordenarTareasPorFecha(): Tarea[]
    + public ordenarTareasPorTitulo(): Tarea[]
}

class GestorDeEstadisticas{
    - tareas: Array<Tarea>
    - buscadorDeTarea: BuscadorDeTarea

    + obtenerTiempoDeFinalizacionDeUnaTarea(tarea: Tarea): number
    + obtenerTiempoDedicadoPorTarea(): Map<number, number>
    + obtenerTiempoDeFinalizacionDeTareas(): number
    + obtenerTiempoPromedioDeFinalizacion(): number
    + obtenercantidadDeTareasPorEstado(): Map<Estado, number>
}

class GestorDeNotificaciones{
    + notificarRecordatorio()
}

abstract class Clasificador{
    - nombre: string

    + getNombre(): string
    + setNombre(nombre: string): void
}

class Categoria {}
class Etiqueta {}

class CreadorDeClasificador{
    + instanciarCategoria(nombre: string): Categoria
    + instanciarEtiqueta(nombre: string): Etiqueta
}

ENUM Estado{
    Pendiente
    EnProgreso
    Completado
}

ENUM Avance{
    0
    25
    50
    75
    100
}

ENUM Prioridad{
    Alta
    Media
    Baja
}

GestorDeEstadisticas <-- Tarea
GestorDeNotificaciones <-- Tarea
OrganizadorDeTarea <-- Tarea
BuscadorDeTarea <-- Tarea
CreadorDeTarea <-- Tarea
GestorDeTarea <-right- Tarea
GestorDeTarea o-up-CreadorDeTarea
GestorDeTarea o-- CreadorDeClasificador
Tarea *-- Categoria
Tarea *-- Etiqueta
Categoria --|> Clasificador
Etiqueta --|> Clasificador
Categoria --> CreadorDeClasificador
Etiqueta --> CreadorDeClasificador
Clasificador -[hidden]- CreadorDeClasificador
Tarea o-right- Estado
Tarea o-right- Avance
Tarea o-right- Prioridad
GestorDeEstadisticas *-left- BuscadorDeTarea
@enduml