@startuml Secuencia 1
title Creación de Tareas

actor Cliente
participant "ListadoDeTareas" as listado
participant "Tarea" as tarea
participant "Categoria" as categoria
participant "Etiqueta" as etiqueta

alt Se requiere categoría o etiquetas
  Cliente -> categoria ++: 1: new Categoria(nombre)
  categoria --> Cliente: nuevaCategoria

  Cliente -> etiqueta ++: 2: new Etiqueta(nombre)
  etiqueta --> Cliente: nuevaEtiqueta
end

Cliente -> listado ++: 3: new ListadoDeTareas()
listado --> Cliente: nuevoListado

Cliente -> tarea ++: 4: new Tarea(titulo, diasParaCompletar)

Cliente -> tarea: 5: Actualizar atributos opcionales
Cliente -> categoria: 6: setCategoria
categoria --> tarea: categoriaAsignada
deactivate categoria

Cliente -> etiqueta: 7: setEtiqueta
etiqueta --> tarea: etiquetaAsignada
deactivate etiqueta

tarea --> Cliente --: 8: nueva tarea

Cliente -> listado: 9: agregarTarea(tarea)
listado --> Cliente --: void
@enduml