plantuml
@startuml Crear Usuario y Agregar a Lista Simple

actor Cliente
participant "Usuario" as user
participant "ListaUsuarios" as list

Cliente -> user ++: new Usuario(nombre, email)
user --> Cliente --: nuevoUsuario

Cliente -> list ++: agregarUsuario(nuevoUsuario)
list -> list: usuarios.add(nuevoUsuario)
list --> Cliente --: confirmación

@enduml